#!/usr/bin/env python3
"""Generate the full demo-pack voice set with Piper TTS (OQ-3 alternative path).

Usage:
  python3 tool/tts_generate.py --model <voice.onnx> [--primary 21] [--secondary 47] [--out content/demo]

Synthesizes every voice clip the demo pack references. Words, narrations,
and vocab definitions are DERIVED from content/demo/manifest.json, so newly
authored stories are voiced automatically; phonemes, prompts, nav, and
celebration lines are fixed sets below.

TWO-VOICE POLICY (owner-ratified 2026-07-29): everything phonics-blending
(phonemes, word pronunciations) uses the PRIMARY voice only -- mixing voices
inside a blended word would undermine the pedagogy. Sentence-level audio
alternates: narrations alternate per story/twister, celebration lines
alternate per line; vocab definitions ride the SECONDARY voice as the
distinct "new word" character; UI prompts/nav stay primary for consistency.

Output is trimmed (leading/trailing silence) but NOT loudness-normalized --
run `dart run tool/normalize_wav.dart content/demo` afterwards, which uses
the app's own BS.1770 implementation to hit exactly -16 LUFS, then rebuild
the pack (the loudness gate re-verifies every clip).

Existing REAL recordings are overwritten only with --force: by default any
file not previously generated by this script (no .tts marker) is skipped.
"""
import argparse
import json
import os
import sys
import wave

from piper import PiperVoice

# ---------------------------------------------------------------------------
# Clip manifest (mirrors docs/audio/recording-checklist.md exactly)
# ---------------------------------------------------------------------------

# ARPAbet id -> espeak-ng phoneme string ([[..]] passthrough). Continuants
# carry ':' length markers so the clip is audible in isolation; stops stay
# short and clean (the brief's "no schwa tail" rule -- [[b]] not "buh").
PHONEMES = {
    "B": "b", "D": "d", "G": "g", "K": "k", "P": "p", "T": "t",
    "JH": "dZ", "CH": "tS",
    "F": "f:", "V": "v:", "S": "s:", "Z": "z:", "SH": "S:", "ZH": "Z:",
    "TH": "T:", "DH": "D:", "HH": "h",
    "M": "m:", "N": "n:", "NG": "N:",
    "L": "l:", "R": "r:", "W": "w:", "Y": "j:",
    "AA": "A:", "AE": "a:", "AH": "V:", "AO": "O:", "AW": "aU:", "AY": "aI:",
    "EH": "E:", "ER": "3:", "EY": "eI:", "IH": "I:", "IY": "i:", "OW": "oU:",
    "OY": "OI:", "UH": "U:", "UW": "u:", "AX": "@:",
    "AIR": "e@:", "EAR": "i@:", "URE": "U@:", "ARE": "A:r",
}

CHEERS = [
    "You did it!", "Great reading!", "Wow, you read that whole page!",
    "Nice job sounding that out!", "You're getting so good at this!",
    "Amazing!", "What a great story!", "You read every word!",
    "Super job!", "That was wonderful reading!",
]

FIXED = {
    "prompts/your_turn.wav": "Your turn.",
    "prompts/near_miss.wav": "Good try! Listen.",
    "audio/nav/map.wav": "The story map.",
    "audio/nav/collection.wav": "Your collection.",
    "audio/nav/garden.wav": "The Sound Garden.",
    "audio/nav/parent-corner.wav": "The parent corner.",
    "audio/nav/flashcards.wav": "Flash cards.",
    "vocab/garden_definition.wav":
        "A garden is a place outside where plants and flowers grow.",
    "vocab/buzzing_definition.wav":
        "Buzzing is the soft humming sound a bug makes with its wings.",
}


def _sentence_text(words):
    return " ".join(w["text"] for w in words) + "."


def manifest(content_dir, primary, secondary):
    """ref -> (text, speaker_id). Words/narrations/vocab derive from the
    authored pack manifest; the rest are fixed sets."""
    clips = {}
    for pid, esp in PHONEMES.items():
        clips[f"phonemes/{pid}.wav"] = (f"[[{esp}]]", primary)

    with open(os.path.join(content_dir, "manifest.json")) as f:
        pack = json.load(f)

    def add_word(token):
        clips[token["pronunciationAudioRef"]] = (token["text"].lower() + ".", primary)

    alternate = 0
    for story in pack.get("stories", []):
        voice = primary if alternate % 2 == 0 else secondary
        alternate += 1
        for page in story.get("pages", []):
            for sentence in page.get("sentences", []):
                for token in sentence.get("words", []):
                    add_word(token)
                ref = sentence.get("narrationAudioRef")
                if ref:
                    clips[ref] = (_sentence_text(sentence["words"]), voice)
    for twister in pack.get("twisters", []):
        voice = primary if alternate % 2 == 0 else secondary
        alternate += 1
        for token in twister.get("words", []):
            add_word(token)
        clips[twister["narrationAudioRef"]] = (_sentence_text(twister["words"]), voice)
    for card in pack.get("vocabCards", []):
        clips[card["definitionAudioRef"]] = (card["definitionText"], secondary)
    for sound in pack.get("graphemeSounds", []):
        for ex in sound.get("exampleWords", []):
            clips.setdefault(ex["pronunciationAudioRef"],
                             (ex["wordText"].lower() + ".", primary))

    for i, line in enumerate(CHEERS, start=1):
        clips[f"celebrations/cheer_{i:02d}.wav"] = (line, primary if i % 2 == 1 else secondary)
    for ref, text in FIXED.items():
        clips[ref] = (text, primary)
    return clips


# ---------------------------------------------------------------------------
# Synthesis + trim
# ---------------------------------------------------------------------------

def trim(frames: bytes, threshold_ratio=0.01, pad_ms=6, rate=22050) -> bytes:
    """Strip leading/trailing near-silence (16-bit mono PCM)."""
    import array
    samples = array.array("h", frames)
    if not samples:
        return frames
    peak = max(1, max(abs(s) for s in samples))
    threshold = peak * threshold_ratio
    start = next((i for i, s in enumerate(samples) if abs(s) >= threshold), 0)
    end = next(
        (len(samples) - i for i, s in enumerate(reversed(samples)) if abs(s) >= threshold),
        len(samples),
    )
    pad = int(rate * pad_ms / 1000)
    start = max(0, start - pad)
    end = min(len(samples), end + pad)
    return samples[start:end].tobytes()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--primary", type=int, default=21)
    ap.add_argument("--secondary", type=int, default=47)
    ap.add_argument("--out", default="content/demo")
    ap.add_argument("--force", action="store_true",
                    help="overwrite files that lack a .tts marker (i.e. real recordings)")
    ap.add_argument("--only", default=None,
                    help="comma-separated ref substrings to regenerate")
    args = ap.parse_args()

    voice = PiperVoice.load(args.model)
    from piper.config import SynthesisConfig
    clips = manifest(args.out, args.primary, args.secondary)
    only = args.only.split(",") if args.only else None

    made, skipped, short = 0, 0, []
    for ref, (text, speaker) in clips.items():
        syn_config = SynthesisConfig(speaker_id=speaker)
        if only and not any(o in ref for o in only):
            continue
        path = os.path.join(args.out, *ref.split("/"))
        marker = path + ".tts"
        if os.path.exists(path) and not os.path.exists(marker) and not args.force:
            # A human recording (or original placeholder) we were not asked
            # to replace. Placeholders shipped before this script existed,
            # so first run: use --force once, then markers take over.
            skipped += 1
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        import io
        buf = io.BytesIO()
        with wave.open(buf, "wb") as w:
            voice.synthesize_wav(text, w, syn_config=syn_config)
        buf.seek(0)
        with wave.open(buf, "rb") as w:
            rate = w.getframerate()
            frames = w.readframes(w.getnframes())
        frames = trim(frames, rate=rate)
        with wave.open(path, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(rate)
            w.writeframes(frames)
        with open(marker, "w") as m:
            json.dump({"speaker": speaker, "text": text}, m)
        seconds = len(frames) / 2 / rate
        if seconds < 0.08:
            short.append((ref, round(seconds, 3)))
        made += 1

    print(f"generated {made}, skipped {skipped} (existing non-TTS files)")
    if short:
        print("WARNING -- suspiciously short clips (check by ear):")
        for ref, s in short:
            print(f"  {ref}: {s}s")
    print("next: dart run tool/normalize_wav.dart", args.out)


if __name__ == "__main__":
    sys.exit(main())
